// src/services/geminiService.ts

import { GoogleGenAI } from "@google/genai";

// Vite 환경에서 클라이언트 측에 노출될 환경 변수를 가져옵니다.
// 변수 이름은 반드시 'VITE_' 접두사로 시작해야 합니다.
// 로컬 개발 시에는 .env.local 파일에서 이 값을 읽어오고,
// Netlify 배포 시에는 Netlify 대시보드에 설정한 환경 변수 값을 읽어옵니다.
const apiKey = import.meta.env.VITE_GEMINI_API_KEY;

// API 키가 설정되지 않았을 경우 에러를 발생시켜 문제를 즉시 파악할 수 있도록 합니다.
if (!apiKey) {
    throw new Error("VITE_GEMINI_API_KEY environment variable not set. Please check your .env.local file or Netlify environment settings.");
}

// 가져온 API 키를 사용하여 GoogleGenAI 클라이언트 인스턴스를 생성합니다.
const ai = new GoogleGenAI({ apiKey });

/**
 * Imagen 모델을 사용하여 픽셀 아트 이미지를 생성하는 비동기 함수입니다.
 * @param userPrompt - 사용자가 입력한 이미지에 대한 텍스트 설명.
 * @returns 생성된 이미지의 Base64 데이터 URL을 담은 Promise 객체.
 */
export const generatePixelArt = async (userPrompt: string): Promise<string> => {
    // 모델이 '픽셀 아트' 스타일을 잘 이해하도록 프롬프트를 강화합니다.
    const fullPrompt = `pixel art style, ${userPrompt}`;

    try {
        console.log("Generating image with prompt:", fullPrompt);
        
        // Google AI의 이미지 생성 API를 호출합니다.
        const response = await ai.models.generateImages({
            model: 'imagen-3.0-generate-002', // 사용할 이미지 생성 모델
            prompt: fullPrompt,               // AI에게 전달할 최종 프롬프트
            config: {
                numberOfImages: 1,            // 생성할 이미지 개수
                outputMimeType: 'image/png',  // 결과 이미지 포맷
                aspectRatio: '1:1',           // 이미지 비율 (정사각형)
            },
        });
        
        console.log("API response received.");

        // API 응답에서 생성된 이미지가 있는지 확인합니다.
        if (response.generatedImages && response.generatedImages.length > 0) {
            // 첫 번째 생성된 이미지의 Base64 인코딩된 바이트 데이터를 가져옵니다.
            const base64ImageBytes = response.generatedImages[0].image.imageBytes;
            
            // 웹 브라우저에서 바로 이미지로 표시할 수 있는 데이터 URL 형식으로 변환하여 반환합니다.
            return `data:image/png;base64,${base64ImageBytes}`;
        } else {
            // 이미지가 생성되지 않은 경우 에러를 발생시킵니다.
            throw new Error("No image was generated by the API.");
        }
    } catch (error) {
        // API 호출 중 발생한 에러를 처리합니다.
        console.error("Error generating image:", error);
        
        // 에러 객체의 종류에 따라 더 구체적인 에러 메시지를 생성하여 반환합니다.
        if (error instanceof Error) {
            throw new Error(`API call failed: ${error.message}`);
        }
        // 알 수 없는 에러가 발생한 경우를 대비한 처리입니다.
        throw new Error("An unknown error occurred during image generation.");
    }
};